/**
 * @fileoverview gRPC-Web generated client stub for chatPackage
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.25.2
// source: proto/chat.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as proto_chat_pb from '../proto/chat_pb';
import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb';


export class ChatServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSignUp = new grpcWeb.MethodDescriptor(
    '/chatPackage.ChatService/SignUp',
    grpcWeb.MethodType.UNARY,
    proto_chat_pb.SignUpRequest,
    proto_chat_pb.User,
    (request: proto_chat_pb.SignUpRequest) => {
      return request.serializeBinary();
    },
    proto_chat_pb.User.deserializeBinary
  );

  signUp(
    request: proto_chat_pb.SignUpRequest,
    metadata: grpcWeb.Metadata | null): Promise<proto_chat_pb.User>;

  signUp(
    request: proto_chat_pb.SignUpRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_chat_pb.User) => void): grpcWeb.ClientReadableStream<proto_chat_pb.User>;

  signUp(
    request: proto_chat_pb.SignUpRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_chat_pb.User) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/chatPackage.ChatService/SignUp',
        request,
        metadata || {},
        this.methodDescriptorSignUp,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/chatPackage.ChatService/SignUp',
    request,
    metadata || {},
    this.methodDescriptorSignUp);
  }

  methodDescriptorSignIn = new grpcWeb.MethodDescriptor(
    '/chatPackage.ChatService/SignIn',
    grpcWeb.MethodType.UNARY,
    proto_chat_pb.SignInRequest,
    proto_chat_pb.User,
    (request: proto_chat_pb.SignInRequest) => {
      return request.serializeBinary();
    },
    proto_chat_pb.User.deserializeBinary
  );

  signIn(
    request: proto_chat_pb.SignInRequest,
    metadata: grpcWeb.Metadata | null): Promise<proto_chat_pb.User>;

  signIn(
    request: proto_chat_pb.SignInRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_chat_pb.User) => void): grpcWeb.ClientReadableStream<proto_chat_pb.User>;

  signIn(
    request: proto_chat_pb.SignInRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_chat_pb.User) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/chatPackage.ChatService/SignIn',
        request,
        metadata || {},
        this.methodDescriptorSignIn,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/chatPackage.ChatService/SignIn',
    request,
    metadata || {},
    this.methodDescriptorSignIn);
  }

  methodDescriptorSendMessage = new grpcWeb.MethodDescriptor(
    '/chatPackage.ChatService/SendMessage',
    grpcWeb.MethodType.UNARY,
    proto_chat_pb.MessageRequest,
    google_protobuf_empty_pb.Empty,
    (request: proto_chat_pb.MessageRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  sendMessage(
    request: proto_chat_pb.MessageRequest,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  sendMessage(
    request: proto_chat_pb.MessageRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  sendMessage(
    request: proto_chat_pb.MessageRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/chatPackage.ChatService/SendMessage',
        request,
        metadata || {},
        this.methodDescriptorSendMessage,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/chatPackage.ChatService/SendMessage',
    request,
    metadata || {},
    this.methodDescriptorSendMessage);
  }

  methodDescriptorUserStream = new grpcWeb.MethodDescriptor(
    '/chatPackage.ChatService/UserStream',
    grpcWeb.MethodType.SERVER_STREAMING,
    proto_chat_pb.StreamRequest,
    proto_chat_pb.UserStreamResponse,
    (request: proto_chat_pb.StreamRequest) => {
      return request.serializeBinary();
    },
    proto_chat_pb.UserStreamResponse.deserializeBinary
  );

  userStream(
    request: proto_chat_pb.StreamRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<proto_chat_pb.UserStreamResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/chatPackage.ChatService/UserStream',
      request,
      metadata || {},
      this.methodDescriptorUserStream);
  }

  methodDescriptorChatStream = new grpcWeb.MethodDescriptor(
    '/chatPackage.ChatService/ChatStream',
    grpcWeb.MethodType.SERVER_STREAMING,
    proto_chat_pb.StreamRequest,
    proto_chat_pb.StreamMessage,
    (request: proto_chat_pb.StreamRequest) => {
      return request.serializeBinary();
    },
    proto_chat_pb.StreamMessage.deserializeBinary
  );

  chatStream(
    request: proto_chat_pb.StreamRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<proto_chat_pb.StreamMessage> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/chatPackage.ChatService/ChatStream',
      request,
      metadata || {},
      this.methodDescriptorChatStream);
  }

}

